sudo: required
dist: trusty
language: node_js
node_js:
  - '5.11'

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: karma start karma.conf.js --single-run
